# Site settings
title: Classy Lens
description: Capturing the beauty of our world
baseurl: "/classy-lens"
url: "" # the base hostname & protocol for your site
author: Gabriel Volpe

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
